version: '3.8'

services:

  adminer:
    image: mlopshw1
    restart: always
    container_name: api_service
    
    ports:
    - "5000:5000"
  
  db:
    image: postgres
    restart: always
    container_name: database_service
    environment:
      POSTGRES_DB: models_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./infile.sql:/docker-entrypoint-initdb.d/infile.sql
    ports:
      - "5432:5432"
  
volumes:
  pg_data:
