# Use postgres/example user/password credentials
version: '3.8'

services:

  adminer:
    image: mlopshw1
    restart: always
    container_name: api_service
    
    ports:
      - "127.0.0.1:5000:5000"
  
  db:
    image: postgres
    restart: always
    container_name: database_service
    environment:
      POSTGRES_DB: models_db
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/MLOps_hw1/database